#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : uk                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://neurise.app                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :  assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :  Neurise                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The science of happiness, made simple.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Neurise                                
your_link                                 : https://neurise.com                     
your_city                                 : Hampshire, UK                                
email_address                             : contact+neurise@codeglee.com
facebook_username                         :                                           
instagram_username                        : neurise.app
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title: Smarter Habits, Every Day
  description: Build science-backed habits that boost your happiness — automatically tailored to your mood, time of day, and goals.
  fontawesome_icon_name: brain

  - title: Backed by Science
  description: Grounded in the latest psychology and behavioral science, our tools are designed to sustainably increase well-being.
  fontawesome_icon_name: flask

  - title: Personalized for You
  description: From gratitude to goal-setting, receive habit suggestions that adapt to your unique personality and daily rhythm.
  fontawesome_icon_name: user-cog

  - title: Track What Lifts You
  description: See which habits actually make you happier, thanks to built-in mood tracking and behavioral insights.
  fontawesome_icon_name: chart-line

  - title: Feel-Good Routines
  description: Discover uplifting rituals — morning to night — proven to boost mood, motivation, and meaning.
  fontawesome_icon_name: sun

  - title: Purposeful Progress
  description: Set goals that matter and feel the momentum. We help you stay aligned with what brings long-term satisfaction.
  fontawesome_icon_name: bullseye

  - title: Built-In Motivation
  description: Smart nudges and positive reinforcement help keep you going — no guilt, just growth.
  fontawesome_icon_name: rocket

  - title: Share the Joy
  description: Connect with others through kindness challenges, shared goals, and uplifting messages.
  fontawesome_icon_name: heart

  - title: Privacy by Design
  description: Your data is safe, secure, and always under your control. Happiness shouldn’t come at the cost of privacy.
  fontawesome_icon_name: lock

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#824EA1"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
